name: apprendre-declencheurs

on:
  # Déclenchement sur le push
  push:
    branches:
      - main
      - develop
    tags:
      - 'v*' # Se déclenche pour v1.0, v2.1.4, etc.

  # Déclenchement sur une Pull Request
  pull_request:
    branches:
      - main

  # Déclenchement manuel
  workflow_dispatch:

jobs:
  affichage-evenement:
    runs-on: ubuntu-latest
    steps:
      - name: Afficher le type d'événement
        run: echo "Déclenché par : ${{ github.event_name }}"